version: "3.9"  # optional since v1.27.0
services:
  webapi:
    image: ${DOCKER_REGISTRY-}netcorewebapi
    build:
      context: .
      dockerfile: .
    ports:
      - "8081:80"
    depends_on:
      - sqldata
    
  sqldata:
    image: mcr.microsoft.com/mssql/server
    environment:
      - SA_PASSWORD=Password#2022
      - ACCEPT_EULA=Y
    volumes:
      - ./data:/var/opt/mssql/data
    ports:
      - "1450:1433"